FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY detect_video_bars.py /app/detect_video_bars.py
COPY api.py /app/api.py

RUN pip install --no-cache-dir flask numpy opencv-python-headless

EXPOSE 5000

CMD ["python3", "api.py"]