---
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "${DOCKER_LOG_MAX_SIZE}"
    max-file: "${DOCKER_LOG_MAX_FILE}"

x-n8n-common-env: &n8n-common-env
  N8N_RUNNERS_ENABLED: "true"
  GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: postgres
  DB_POSTGRESDB_PORT: 5432
  DB_POSTGRESDB_DATABASE: n8ndb
  DB_POSTGRESDB_USER: n8n
  DB_POSTGRESDB_PASSWORD: NJNf^DDeUa2jyt4
  N8N_DEFAULT_BINARY_DATA_MODE: filesystem
  N8N_BINARY_DATA_STORAGE_PATH: /files
  EXECUTIONS_MODE: queue
  QUEUE_BULL_REDIS_HOST: redis
  QUEUE_BULL_REDIS_PORT: 6379
  N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
  OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"

x-n8n-common: &n8n-common
  build:
    context: .
    dockerfile: Dockerfile
  restart: always
  pull_policy: if_not_present
  depends_on:
    - postgres
    - redis
  logging: *default-logging
  volumes:
    - n8n-data:/home/node/.n8n
    - ${DEPLOY_FOLDER}/local_files:/files
    - ./binary_data:/files
  networks:
    - n8n_network
  environment:
    <<: *n8n-common-env

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    pull_policy: if_not_present
    container_name: postgres_n8n_docker
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: NJNf^DDeUa2jyt4
      POSTGRES_DB: n8ndb
    logging: *default-logging
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - n8n_network

  redis:
    image: redis:7-alpine
    restart: always
    pull_policy: if_not_present
    logging: *default-logging
    volumes:
      - redis-data:/data
    networks:
      - n8n_network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    pull_policy: always
    container_name: caddy_n8n_docker
    ports:
      - "80:80"
      - "443:443"
    logging: *default-logging
    volumes:
      - ${DEPLOY_FOLDER}/caddy_data:/data
      - ${DEPLOY_FOLDER}/caddy_config:/config
      - ${DEPLOY_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile
      - ${DEPLOY_FOLDER}/caddy_config/certs:/certs
    networks:
      - n8n_network

  n8n:
    <<: *n8n-common
    container_name: n8n_docker
    environment:
      <<: *n8n-common-env
      N8N_BASIC_AUTH_ACTIVE: "false"
      N8N_HOST: ${DOMAIN_NAME}
      WEBHOOK_URL: https://${DOMAIN_NAME}
      N8N_PROTOCOL: https
      N8N_PROXY_HOPS: 1
      N8N_SECURE_COOKIE: "false"
      

  n8n-worker-1:
    <<: *n8n-common
    command: worker --concurrency=1

  n8n-worker-2:
    <<: *n8n-common
    command: worker --concurrency=1

  n8n-worker-3:
    <<: *n8n-common
    command: worker --concurrency=1

  n8n-worker-4:
    <<: *n8n-common
    command: worker --concurrency=1

volumes:
  n8n-data:
  postgres-data:
  redis-data:

networks:
  n8n_network:
    driver: bridge