version: "3.8"

x-n8n-env: &n8n-env
  GENERIC_TIMEZONE: Asia/Ho_Chi_Minh
  TZ: Asia/Ho_Chi_Minh
  EXECUTIONS_MODE: queue
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: postgres
  DB_POSTGRESDB_PORT: 5432
  DB_POSTGRESDB_DATABASE: n8n
  DB_POSTGRESDB_USER: n8n
  DB_POSTGRESDB_PASSWORD: n8n
  QUEUE_BULL_REDIS_HOST: redis
  QUEUE_BULL_REDIS_PORT: 6379
  N8N_ENCRYPTION_KEY: P6QhfMJONZnzDLKv+Pvlf+35ZXESD5SW
  N8N_RUNNERS_ENABLED: "true"
  N8N_RUNNERS_MODE: internal
  OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"

x-n8n-worker-volumes: &n8n-worker-volumes
  - /home/vmo/Downloads/final-video-1:/tmp/final-video-1
  - /home/vmo/Downloads/final-video-2:/tmp/final-video-2
  - /home/vmo/Downloads/final-video-3:/tmp/final-video-3
  - /home/vmo/Downloads/final-video-4:/tmp/final-video-4

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    environment:
      <<: *n8n-env
      NODE_ENV: production
      N8N_CONCURRENCY_PRODUCTION_LIMIT: 2
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  n8n-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
    command: worker
    environment:
      <<: *n8n-env
      N8N_CONCURRENCY_PRODUCTION_LIMIT: 5
    restart: unless-stopped
    volumes: *n8n-worker-volumes
    depends_on:
      - postgres
      - redis

  n8n-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
    command: worker
    environment:
      <<: *n8n-env
      N8N_CONCURRENCY_PRODUCTION_LIMIT: 5
    restart: unless-stopped
    volumes: *n8n-worker-volumes
    depends_on:
      - postgres
      - redis

  n8n-worker-3:
    build:
      context: .
      dockerfile: Dockerfile
    command: worker
    environment:
      <<: *n8n-env
      N8N_CONCURRENCY_PRODUCTION_LIMIT: 5
    restart: unless-stopped
    volumes: *n8n-worker-volumes
    depends_on:
      - postgres
      - redis

  n8n-worker-4:
    build:
      context: .
      dockerfile: Dockerfile
    command: worker
    environment:
      <<: *n8n-env
      N8N_CONCURRENCY_PRODUCTION_LIMIT: 5
    restart: unless-stopped
    volumes: *n8n-worker-volumes
    depends_on:
      - postgres
      - redis

volumes:
  n8n_data:
  pgdata:
